--1
SELECT DEPENDENT_NAME, D.SEX
FROM DEPENDENT AS D INNER JOIN EMPLOYEE E ON ESSN=SSN
WHERE D.SEX ='F' AND E.SEX='F'
UNION
SELECT D.DEPENDENT_NAME, D.SEX
FROM Dependent D INNER JOIN Employee E ON ESSN=SSN
WHERE D.SEX='M' AND E.SEX='M';

--2
SELECT PNAME, SUM(HOURS) AS TOTAL_HOURS
FROM PROJECT , Works_for
WHERE PNUMBER = PNO
GROUP BY PNAME;

--3
SELECT D.* FROM Departments D, Employee
WHERE DNO=DNUM AND SSN IN (SELECT MIN(SSN) FROM Employee);

--4
SELECT DNAME, MIN(SALARY)AS MIN, MAX(SALARY) AS MAX, AVG(SALARY)AS AVG
FROM Departments INNER JOIN Employee ON DNUM=DNO 
GROUP BY DNAME;

--5
SELECT LNAME 
FROM Employee INNER JOIN Departments ON MGRSSN=SSN
LEFT JOIN DEPENDENT ON SSN=ESSN
WHERE ESSN IS NULL;

--6
SELECT DNUM, DNAME, COUNT(SSN) AS 'NUMBER OF EMPLOYEES'
FROM Departments, Employee
WHERE DNUM=DNO
GROUP BY DNAME, DNUM
HAVING AVG(SALARY) < (SELECT AVG(SALARY) FROM Employee);

--7
SELECT FNAME, LNAME AS NAME, PNAME
FROM Employee INNER JOIN Departments D ON DNUM=DNO
INNER JOIN PROJECT P ON P.Dnum=D.DNUM
ORDER BY D.DNUM, FNAME, LNAME;

--8
SELECT MAX(SALARY)
FROM Employee
UNION ALL
SELECT MAX(SALARY)
FROM Employee
WHERE SALARY NOT IN (SELECT MAX(SALARY) FROM Employee);
--ANOTHER SOLUTION
SELECT TOP 3(SALARY)
FROM Employee ORDER BY SALARY DESC;


--9
SELECT FNAME+' '+LNAME AS FULL_NAME
FROM Employee INTERSECT SELECT Dependent_NAME FROM Dependent;

--10
update EMPLOYEE SET SALARY += .3*SALARY
FROM EMPLOYEE, WORKS_FOR, PROJECT
WHERE PROJECT.PNAME='AL RABWAH' AND PNO=PNUMBER AND ESSN=SSN;

--11
select SSN, FNAME
FROM Employee
WHERE EXISTS( SELECT ESSN FROM Dependent);

--1
insert into Departments
values('DEPT IT',100,112233,11/1/2006);

--2
UPDATE Departments SET MGRSSN = 968574 WHERE Dnum=100;
UPDATE Departments SET MGRSSN = 102672 WHERE Dnum=20;
UPDATE Employee SET Superssn=102672 WHERE SSN=102660 ;

--3
UPDATE Employee SET Superssn=102672 WHERE Superssn=223344;
UPDATE Departments SET MGRSSN=102672 WHERE MGRSSN=223344;
DELETE Dependent WHERE ESSN=223344;
DELETE Works_for WHERE ESSN=223344;
DELETE Employee WHERE SSN=223344;
