--1
SELECT * FROM EMPLOYEE;

--2
SELECT FNAME, LNAME, SALARY, DNO FROM EMPLOYEE;

--3
SELECT PNAME, PLOCATION, DNUM FROM PROJECT;

--4
SELECT FNAME+' '+LNAME AS FULLNAME, (12*SALARY)*.1 AS ANNUAL_COMM FROM EMPLOYEE;


--5
SELECT SSN, FNAME+' '+LNAME AS NAME FROM EMPLOYEE WHERE SALARY>1000;

--6
SELECT SSN, FNAME+' '+LNAME AS NAME FROM EMPLOYEE WHERE (SALARY*12)>10000;

--7
SELECT FNAME+' '+LNAME AS Name, SALARY  FROM EMPLOYEE WHERE SEX='F';

--8
SELECT DNUMBER, DNAME FROM DEPARTMENT WHERE MGRSSN=968574;

--9
SELECT PNUMBER, PNAME, PLOCATION FROM PROJECT WHERE DNUM=10;
