--1)Create Database using wizard with the following schema then 
--Create DB Diagram and insert at least 2 rows per table 
create database company;
use wizard;
CREATE TABLE EMPLOYEE(
	FNAME VARCHAR(50),
	MINIT VARCHAR(50),
	LNAME VARCHAR(50),
	SSN INT PRIMARY KEY,
	BDATE DATETIME,
	ADDRESS VARCHAR(50),
	SEX VARCHAR(1),
	SALARY INT,
	SUPERSSN INT FOREIGN KEY REFERENCES EMPLOYEE(SSN),
	--DNO INT FOREIGN KEY REFERENCES DEPARTMENT(DNO)
);

CREATE TABLE DEPARTMENT(
	DNAME VARCHAR(50),
	DNUMBER INT PRIMARY KEY,
	MGRSSN INT FOREIGN KEY REFERENCES EMPLOYEE(SSN),
	MGRStartDate DATETIME
);

CREATE TABLE DEPT_LOCATIONS(
	DNUMBER INT,
	DLOCATION VARCHAR(250),
	PRIMARY KEY(DNUMBER, DLOCATION),
	FOREIGN KEY(DNUMBER) REFERENCES DEPARTMENT(DNUMBER)
);

CREATE TABLE PROJECT(
	PNAME VARCHAR(50),
	PNUMBER INT PRIMARY KEY,
	PLOCATION VARCHAR(250),
	DNUM INT FOREIGN KEY REFERENCES DEPARTMENT(DNUMBER)
);

CREATE TABLE WORKS_ON(
	ESSN INT FOREIGN KEY REFERENCES EMPLOYEE(SSN),
	PNO INT FOREIGN KEY REFERENCES PROJECT(PNUMBER),
	HOURS INT,
	PRIMARY KEY(ESSN, PNO)
);

CREATE TABLE DEPENDENT (
	ESSN INT FOREIGN KEY REFERENCES EMPLOYEE(SSN),
	DEPENDENT_NAME VARCHAR(50),
	SEX VARCHAR(1),
	BDATE DATETIME,
	RELATIONSHIP VARCHAR(50),
	PRIMARY KEY(ESSN, DEPENDENT_NAME)
);

INSERT INTO EMPLOYEE VALUES('YASSIN', 'M4_3ARF', 'aLI', 10, NULL, 'EL-HARAM', 'M', 5000, NULL);
INSERT INTO EMPLOYEE VALUES('YASSO', 'M4_3ARF', 'ALI', 20, NULL, 'EL-HARAM_STREET', 'M', 10000, 10);

INSERT INTO DEPARTMENT VALUES('YAS', 10, 10, '2008-04-02 00:00:00.000');
INSERT INTO DEPARTMENT VALUES('YASSS', 20, NULL, '2008-04-02 00:00:00');

INSERT INTO DEPT_LOCATIONS VALUES(10, 'EL-KONAYSA');
INSERT INTO DEPT_LOCATIONS VALUES(20, 'EL-HARAM2');

INSERT INTO PROJECT VALUES('AGMD-PROJECT', 10, 'EL-HARAM-TANY', 20);
INSERT INTO PROJECT VALUES('TANY-AGMD-PROJECT', 20, 'EL-HARAM-TALT', 10);

INSERT INTO WORKS_ON VALUES(10, 10, 10);
INSERT INTO WORKS_ON VALUES(20, 20, 20);

INSERT INTO DEPENDENT VALUES(10, 'DS', 'M', '2005-01-04 00:00:00.000', 'AY_7AGA');
INSERT INTO DEPENDENT VALUES(20, 'IS', 'M', '2005-5-4 00:00:00', 'AY_7AGA');

---------------------------------------------------------------------

--2)Restore Company DB then
USE Company_SD;

--1
SELECT * FROM EMPLOYEE;

--2
SELECT FNAME, LNAME, SALARY, DNO
FROM Employee;

--3
SELECT PNAME, PLOCATION, DNAME FROM PROJECT, Departments WHERE PROJECT.DNUM=Departments.DNUM;

--4
SELECT FNAME+' '+LNAME AS FULL_NAME, (12*SALARY)*.1 AS ANNUAL_COMM
FROM Employee;

--5
SELECT SSN, FNAME+' '+LNAME AS FULL_NAME FROM Employee WHERE SALARY>1000;

--6
SELECT SSN, FNAME+' '+LNAME AS FULL_NAME FROM Employee WHERE 12*SALARY>10000;

--7
SELECT FNAME+' '+LNAME AS FULL_NAME, SALARY FROM EMPLOYEE WHERE SEX='F';

--8
SELECT DNUM, DNAME FROM Departments WHERE MGRSSN=968574;

--9
SELECT PNUMBER, PNAME, PLOCATION FROM Project WHERE DNUM = 10;

